/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMdiAccountCircleOutline: typeof import('~icons/mdi/account-circle-outline')['default']
    IconMdiAlphaFCircle: typeof import('~icons/mdi/alpha-f-circle')['default']
    IconMdiFlagVariant: typeof import('~icons/mdi/flag-variant')['default']
    IconMdiFlagVariantPlus: typeof import('~icons/mdi/flag-variant-plus')['default']
    IconMdiNullOff: typeof import('~icons/mdi/null-off')['default']
    IconMdiPeopleAdd: typeof import('~icons/mdi/people-add')['default']
    ModalCreateStandings: typeof import('./src/components/ModalCreateStandings.vue')['default']
  }
}
